spring:
  profiles.active: dev
  devtools.restart:
    enabled: false
    exclude: color-store-fe/**

blockchain:
  node.address: "http://127.0.0.1:8545" # address of Ganache personal blockchain; the term "node" provides more flexibility in case this system moves to live ETH blockchain
  contracts:
    color-coin.address: "0x0000000000000000000000000000000000000000" # "contract address" output by truffle migrate command
    color-store.address: "0x0000000000000000000000000000000000000000" # "contract address" output by truffle migrate command

media:
  url: "http://192.168.178.20:8080/images/"
