spring.devtools.restart:
  enabled: false
  exclude: color-store-fe/**

blockchain:
  node.address: "http://127.0.0.1:8545" # address of Ganache personal blockchain; the term "node" provides more flexibility in case this system moves to live ETH blockchain
  contracts:
    color-coin.address: "0x033B7D0B41AccecA44063E4d87a36261A3A592D0" # "contract address" output by truffle migrate command

media:
  url: "http://127.0.0.1:8080/images/"
