spring.devtools.restart:
  enabled: false
  exclude: color-store-fe/**

blockchain:
  node.address: "http://127.0.0.1:8545" # address of Ganache personal blockchain; the term "node" provides more flexibility in case this system moves to live ETH blockchain
  contracts:
    color-coin.address: "0x7811a336436B0D08021D189704937Fd23656b509" # "contract address" output by truffle migrate command
    color-store.address: "0xe43c04f86AFDEf6E1b70fF1Fd15Cad7288B814cc" # "contract address" output by truffle migrate command

media:
  url: "http://127.0.0.1:8080/images/"
